branch-defaults:
  main:
    environment: New-env
environment-defaults:
  New-env:
    branch: null
    repository: null
global:
  application_name: new
  default_ec2_keyname: elbapplication
  default_platform: Node.js 22
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
